export const brandLessons = [
  {
    slug: "brand-01-networking-safely", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 1,
    title: "Networking Safely on Social Media", sourceUrl: "https://docs.google.com/presentation/d/1jrxnF_i-sNvL8c4ufo_2gYWxmtHq2idt/edit", duration: 60,
    summary: "Separate personal sharing from professional positioning, use each platform for its strengths, and build relationships through useful, safe, and consistent participation.",
    summarySw: "Tenganisha kushiriki binafsi na kujenga taswira ya kitaalamu, tumia kila jukwaa kwa nguvu zake na jenga mahusiano kwa ushiriki wenye manufaa, usalama na uthabiti.",
    summaryFr: "Distinguez le partage personnel du positionnement professionnel, utilisez chaque plateforme selon ses forces et développez des relations par une participation utile, sûre et régulière.",
    activity: "Create a two-column plan of content that belongs on a professional profile and content that should remain private. Add one networking message that offers value before asking for help.",
    topics: [
      { term: "Platform fit", definition: "Choosing a social platform because its audience, content format, and norms match the goal you are trying to achieve." },
      { term: "Personal brand", definition: "The credible pattern of skills, values, voice, and proof of work that other people associate with you." },
      { term: "Safe networking", definition: "Building professional relationships without exposing private data, sharing confidential material, or trusting unverified requests." },
    ],
  },
  {
    slug: "brand-02-workspace-productivity", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 2,
    title: "Workspace Productivity", sourceUrl: "https://docs.google.com/presentation/d/17tMFFYdvrilMfjlXtaTHO3YI7R8UYf3_/edit", duration: 60,
    summary: "Use Gmail and cloud office tools as one organized system for communication, file storage, collaboration, and professional project delivery.",
    summarySw: "Tumia Gmail na zana za ofisi mtandaoni kama mfumo mmoja uliopangwa wa mawasiliano, kuhifadhi faili, ushirikiano na kukamilisha miradi ya kitaalamu.",
    summaryFr: "Utilisez Gmail et les outils bureautiques en ligne comme un système organisé de communication, stockage, collaboration et livraison de projets professionnels.",
    activity: "Set up a project folder, a clear naming convention, a shared document with commenter access, and a short email that links to the correct file instead of attaching duplicates.",
    topics: [
      { term: "Single source of truth", definition: "One agreed current file or record that a team uses instead of maintaining conflicting copies in many places." },
      { term: "Naming convention", definition: "A repeatable file-name pattern containing useful details such as project, document type, date, or version." },
      { term: "Collaboration permission", definition: "The minimum access level a person needs to view, comment on, or edit shared work safely." },
    ],
  },
  {
    slug: "brand-03-no-code-automation", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 3,
    title: "No-Code & Desktop Automation", sourceUrl: "https://docs.google.com/presentation/d/1-Vb5KqUlp1vMPEnqWnyZ9ZS-vkrvSHeB/edit", duration: 60,
    summary: "Compare visual app automation with desktop scripting, then design a trigger-action workflow that saves time without hiding mistakes or removing necessary review.",
    summarySw: "Linganisha uendeshaji wa programu kwa picha na uandishi wa skripti za kompyuta, kisha buni mtiririko wa kichocheo na kitendo unaookoa muda bila kuficha makosa.",
    summaryFr: "Comparez l’automatisation visuelle entre applications et les scripts de bureau, puis concevez un flux déclencheur-action qui fait gagner du temps sans masquer les erreurs.",
    activity: "Choose one repeated task and decide whether Zapier or a desktop macro is a better fit. Draw the trigger, data, action, failure case, and manual review point.",
    topics: [
      { term: "No-code automation", definition: "A visual workflow that connects tools and data without requiring the user to write a full program." },
      { term: "Desktop script", definition: "A short program that automates keyboard, mouse, file, or application actions on a local computer." },
      { term: "Failure path", definition: "The planned response when input is missing, a connection fails, permissions change, or an automation produces an unexpected result." },
    ],
  },
  {
    slug: "brand-04-web-credibility", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 4,
    title: "Web Credibility & User Experience", sourceUrl: "https://docs.google.com/presentation/d/1qOljoSL7do19C9NyKg7OdT4Op83ZPgrj/edit", duration: 60,
    summary: "Build trust online with fast, mobile-friendly pages, consistent visual choices, clear navigation, accessible contrast, and content written for the visitor’s task.",
    summarySw: "Jenga uaminifu mtandaoni kwa kurasa za haraka zinazofanya kazi kwenye simu, mwonekano thabiti, urambazaji wazi, utofauti unaosomeka na maudhui ya kazi ya mtumiaji.",
    summaryFr: "Inspirez confiance avec des pages rapides et mobiles, des choix visuels cohérents, une navigation claire, un contraste accessible et un contenu centré sur la tâche du visiteur.",
    activity: "Run a five-second test on a portfolio homepage. Ask a partner what the owner does, what proof they saw, and what they would click next; revise the weakest answer.",
    topics: [
      { term: "Credibility signal", definition: "Evidence that reduces uncertainty, such as clear contact details, real work examples, consistent design, current information, and transparent claims." },
      { term: "Accessibility", definition: "Designing content and controls so people with different abilities, devices, and connection conditions can perceive and use them." },
      { term: "Performance", definition: "How quickly and reliably a page becomes useful, especially on slower networks and lower-powered devices." },
    ],
  },
  {
    slug: "brand-05-python-basics", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 5,
    title: "Python Basics for Automation", sourceUrl: "https://docs.google.com/presentation/d/1gJESxg_2MEhc2O5SH3QjT80oIvm0dbwc/edit", duration: 60,
    summary: "Learn Python’s readable syntax and core data types, then combine input, variables, operators, conditions, and loops into a small useful script.",
    summarySw: "Jifunze sintaksia rahisi na aina kuu za data za Python, kisha unganisha ingizo, vigezo, oparesheni, masharti na vitanzi katika skripti ndogo yenye manufaa.",
    summaryFr: "Apprenez la syntaxe lisible et les types de base de Python, puis combinez entrées, variables, opérateurs, conditions et boucles dans un petit script utile.",
    activity: "Write a program that asks for the cost and quantity of three products, calculates each total, and prints a warning when a total exceeds a chosen budget.",
    topics: [
      { term: "Data type", definition: "The kind of value stored in a program—such as text, whole number, decimal, boolean, or collection—which determines valid operations." },
      { term: "Expression", definition: "A combination of values, variables, and operators that Python evaluates to produce a new value." },
      { term: "Program flow", definition: "The order in which statements run, including branches that choose a path and loops that repeat work." },
    ],
  },
  {
    slug: "brand-06-python-collections", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 6,
    title: "Python Collections & Libraries", sourceUrl: "https://docs.google.com/presentation/d/1Q3hUf88aITkbMqNmmGRuOr8b5Yag-h2D/edit", duration: 60,
    summary: "Organize real-world information with lists, tuples, and dictionaries, and extend Python with libraries rather than rebuilding common tools from scratch.",
    summarySw: "Panga taarifa za ulimwengu halisi kwa listi, tuple na kamusi, na panua Python kwa maktaba badala ya kujenga upya zana za kawaida.",
    summaryFr: "Organisez des informations réelles avec des listes, tuples et dictionnaires, puis étendez Python avec des bibliothèques au lieu de recréer des outils courants.",
    activity: "Create a dictionary for one portfolio project with title, skills, year, and outcomes. Put three project dictionaries in a list and print a formatted project index.",
    topics: [
      { term: "Mutable collection", definition: "A data structure, such as a list or dictionary, whose contents can be added, removed, or changed after creation." },
      { term: "Immutable collection", definition: "A structure, such as a tuple, whose stored values cannot be changed after creation." },
      { term: "Library", definition: "Reusable code packaged to solve common problems so developers can import tested capabilities into their own programs." },
    ],
  },
  {
    slug: "brand-07-responsible-ai", track: "Managing a Personal Brand", trackSlug: "personal-brand", week: 7,
    title: "Responsible AI for Everyday Work", sourceUrl: "https://docs.google.com/presentation/d/1DZjg0WbdtZviYp55NGRib-NSr-Ez7FxO/edit", duration: 60,
    summary: "Use generative and agentic AI as assistants—not authorities—by supplying context, protecting sensitive information, checking results, and retaining ownership of decisions.",
    summarySw: "Tumia AI zalishi na AI tendaji kama wasaidizi, si mamlaka, kwa kutoa muktadha, kulinda taarifa nyeti, kuhakiki matokeo na kubaki na uamuzi wa mwisho.",
    summaryFr: "Utilisez l’IA générative et agentique comme assistante, pas comme autorité, en donnant du contexte, en protégeant les données sensibles, en vérifiant les résultats et en gardant la décision finale.",
    activity: "Use AI to draft a short professional bio without providing private details. Mark every claim that needs proof, revise the tone yourself, and record what the human changed.",
    topics: [
      { term: "Agentic AI", definition: "An AI system designed to plan or perform actions toward a goal, often by using tools, data, or multiple steps." },
      { term: "Prompt context", definition: "Relevant background about audience, goal, constraints, source material, and desired format that helps a model produce a useful response." },
      { term: "Human accountability", definition: "The principle that a person remains responsible for checking, approving, and owning the impact of AI-assisted work." },
    ],
  },
];
