export const professionalLessons = [
  {
    slug: "professional-01-resumes-and-email", track: "Professional Foundations", trackSlug: "professional-foundations", week: 1,
    title: "Resumes & Professional Email", sourceUrl: "https://docs.google.com/presentation/d/1cr3aGwDPwAkaLvaHTBsTqTyv76j2Fc93/edit", duration: 60,
    summary: "Build a clear, achievement-focused resume and write professional emails that make a strong first impression for jobs, partnerships, and entrepreneurship.",
    summarySw: "Jenga wasifu wa kazi ulio wazi unaoonyesha mafanikio, na uandike barua pepe za kitaalamu zinazotoa taswira nzuri kwa ajira, ushirikiano na ujasiriamali.",
    summaryFr: "Créez un CV clair axé sur vos réalisations et rédigez des courriels professionnels qui donnent une excellente première impression pour l’emploi et l’entrepreneuriat.",
    activity: "Choose a real opportunity. Rewrite one resume bullet with a measurable result, then draft a five-sentence email that introduces yourself and asks for a next step.",
    topics: [
      { term: "Targeted resume", definition: "A resume adjusted to match the skills and keywords in one specific opportunity instead of sending the same document everywhere." },
      { term: "Quantified achievement", definition: "A result described with numbers, time, scale, or impact so a reader can understand what changed because of your work." },
      { term: "Professional email", definition: "A concise message with a useful subject, respectful greeting, clear purpose, requested next step, and complete signature." },
    ],
  },
  {
    slug: "professional-02-social-media-safety", track: "Professional Foundations", trackSlug: "professional-foundations", week: 2,
    title: "Social Media, Safety & Networking", sourceUrl: "https://docs.google.com/presentation/d/1O9IHbVn5bCaGKdHqgh71fT9Bso0GlLaG/edit", duration: 60,
    summary: "Use social platforms intentionally: protect your account, shape a credible professional presence, and build relationships without sharing information that creates risk.",
    summarySw: "Tumia mitandao ya kijamii kwa makusudi: linda akaunti yako, jenga taswira ya kitaalamu na uunde mahusiano bila kushiriki taarifa zinazoweza kukuweka hatarini.",
    summaryFr: "Utilisez les réseaux sociaux avec intention : protégez votre compte, construisez une présence professionnelle crédible et développez votre réseau sans exposer d’informations sensibles.",
    activity: "Audit a sample social profile. Mark what builds trust, what should stay private, and one change that would make the profile more useful for networking.",
    topics: [
      { term: "Digital footprint", definition: "The lasting record created by posts, comments, likes, profiles, and other online activity that can shape how others see you." },
      { term: "Professional network", definition: "A group of people and organizations connected through shared work, learning, or goals who can exchange knowledge and opportunities." },
      { term: "Account safety", definition: "Using unique passwords, multi-factor authentication, privacy controls, and careful link checking to reduce the chance of account loss or fraud." },
    ],
  },
  {
    slug: "professional-03-google-workspace", track: "Professional Foundations", trackSlug: "professional-foundations", week: 3,
    title: "Google Workspace Essentials", sourceUrl: "https://docs.google.com/presentation/d/1HQhAhFOIp7cPQrQjhD4-aRHKx5SdRLVk/edit", duration: 60,
    summary: "Organize cloud files, communicate through Gmail, and collaborate safely in Docs, Sheets, Slides, and Drive using the right sharing permission.",
    summarySw: "Panga faili za mtandaoni, wasiliana kwa Gmail na ushirikiane kwa usalama katika Docs, Sheets, Slides na Drive kwa kutumia ruhusa sahihi za kushiriki.",
    summaryFr: "Organisez vos fichiers dans le cloud, communiquez avec Gmail et collaborez en toute sécurité dans Docs, Sheets, Slides et Drive grâce aux bons droits de partage.",
    activity: "Create a project folder with three named subfolders, add one document to each, and explain when a collaborator should be an editor, commenter, or viewer.",
    topics: [
      { term: "Cloud workspace", definition: "A set of online tools that saves work centrally so it can be opened, edited, and synchronized across devices." },
      { term: "File organization", definition: "A consistent system of descriptive names, folders, stars, and versions that makes information quick to find and hard to lose." },
      { term: "Sharing permission", definition: "The access level—viewer, commenter, or editor—that controls what another person can do with a file." },
    ],
  },
  {
    slug: "professional-04-workflow-automation", track: "Professional Foundations", trackSlug: "professional-foundations", week: 4,
    title: "Workflow Automation", sourceUrl: "https://docs.google.com/presentation/d/1J2hoYMyflVerIFpDrqhXino4aQefWUZi/edit", duration: 60,
    summary: "Turn repetitive work into reliable workflows by connecting a trigger to one or more actions, testing the result, and adding conditions only when they are useful.",
    summarySw: "Badili kazi zinazojirudia kuwa mtiririko wa kazi wa kuaminika kwa kuunganisha kichocheo na vitendo, kupima matokeo na kuongeza masharti pale yanapohitajika.",
    summaryFr: "Transformez les tâches répétitives en flux fiables en reliant un déclencheur à des actions, en testant le résultat et en ajoutant des conditions utiles.",
    activity: "Sketch a paper automation for a low-resource classroom: when a learner submits a form, add a row to a sheet and prepare a short confirmation message.",
    topics: [
      { term: "Trigger", definition: "The event that starts an automated workflow, such as a new form response or a newly added spreadsheet row." },
      { term: "Action", definition: "The task performed automatically after a trigger, such as creating a record, sending a message, or updating a file." },
      { term: "Workflow test", definition: "A controlled run with sample data used to confirm field mapping, permissions, and outcomes before an automation is activated." },
    ],
  },
  {
    slug: "professional-05-good-websites", track: "Professional Foundations", trackSlug: "professional-foundations", week: 5,
    title: "Good Websites & Web Development", sourceUrl: "https://docs.google.com/presentation/d/12VFI6Gnlyln0jqrNbfJjcsmgZ9pCgEyp/edit", duration: 60,
    summary: "Evaluate websites through usability, accessibility, performance, mobile design, and content clarity while learning how HTML, CSS, and JavaScript work together.",
    summarySw: "Tathmini tovuti kwa urahisi wa matumizi, ufikivu, kasi, muundo wa simu na uwazi wa maudhui huku ukijifunza jinsi HTML, CSS na JavaScript zinavyoshirikiana.",
    summaryFr: "Évaluez les sites selon leur utilisabilité, accessibilité, performance, adaptation mobile et clarté, tout en comprenant le rôle de HTML, CSS et JavaScript.",
    activity: "Compare two familiar websites on a phone. Score navigation, contrast, speed, and clarity from one to five, then propose the single highest-impact improvement.",
    topics: [
      { term: "User experience", definition: "How understandable, efficient, accessible, and satisfying a website feels to the people trying to complete a task." },
      { term: "Responsive design", definition: "A layout that adapts its content, navigation, and controls to work well on phones, tablets, and larger screens." },
      { term: "Web stack", definition: "HTML provides structure, CSS controls presentation, and JavaScript adds behavior and interaction to a web page." },
    ],
  },
  {
    slug: "professional-06-python-introduction", track: "Professional Foundations", trackSlug: "professional-foundations", week: 6,
    title: "Introduction to Python", sourceUrl: "https://docs.google.com/presentation/d/1u2VQJ09dq6mODS5IpAkQryAPufRc7xF9/edit", duration: 60,
    summary: "Write a first Python program using values, variables, input, operators, decisions, and loops while learning why readable syntax makes Python beginner-friendly.",
    summarySw: "Andika programu yako ya kwanza ya Python kwa kutumia thamani, vigezo, ingizo, oparesheni, maamuzi na vitanzi, na uone kwa nini sintaksia rahisi husaidia wanaoanza.",
    summaryFr: "Écrivez votre premier programme Python avec des valeurs, variables, entrées, opérateurs, décisions et boucles, et découvrez pourquoi sa syntaxe lisible convient aux débutants.",
    activity: "Build a small score checker that asks for a name and score, prints a personalized message, and uses a condition to suggest the next learning step.",
    topics: [
      { term: "Variable", definition: "A clearly named place that stores a value so a program can reuse or change it later." },
      { term: "Conditional", definition: "An if, elif, or else branch that lets a program choose what to do after evaluating a true-or-false expression." },
      { term: "Loop", definition: "A structure that repeats an instruction for each item or while a condition remains true." },
    ],
  },
  {
    slug: "professional-07-python-data-structures", track: "Professional Foundations", trackSlug: "professional-foundations", week: 7,
    title: "Python Data Structures", sourceUrl: "https://docs.google.com/presentation/d/1EzfSv_lQayzrqxqo2OCLAKhBlZWx9s56/edit", duration: 60,
    summary: "Choose between lists, tuples, and dictionaries to store related information, then use common methods and libraries to solve practical problems.",
    summarySw: "Chagua kati ya listi, tuple na kamusi kuhifadhi taarifa zinazohusiana, kisha tumia mbinu na maktaba za kawaida kutatua matatizo halisi.",
    summaryFr: "Choisissez entre listes, tuples et dictionnaires pour stocker des informations liées, puis utilisez leurs méthodes et des bibliothèques pour résoudre des problèmes concrets.",
    activity: "Model a small shop inventory as a list of dictionaries. Add an item, update its quantity, and print the names of products that are low in stock.",
    topics: [
      { term: "List", definition: "An ordered, mutable collection suited to data that may grow, shrink, or change while a program runs." },
      { term: "Tuple", definition: "An ordered, immutable collection suited to values that belong together and should not be changed." },
      { term: "Dictionary", definition: "A mutable collection of key-value pairs that retrieves a value by a meaningful key rather than only by position." },
    ],
  },
  {
    slug: "professional-08-ai-everyday-life", track: "Professional Foundations", trackSlug: "professional-foundations", week: 8,
    title: "AI in Everyday Life", sourceUrl: "https://docs.google.com/presentation/d/1s8Xxh_j01BdUYiPhLwx9nkoa-R9UCGQg/edit", duration: 60,
    summary: "Understand how data powers machine learning and generative AI, write more useful prompts, and verify outputs before using them in school, work, or public communication.",
    summarySw: "Elewa jinsi data inavyoendesha ujifunzaji wa mashine na AI zalishi, andika maelekezo bora na uhakiki matokeo kabla ya kuyatumia shuleni, kazini au hadharani.",
    summaryFr: "Comprenez comment les données alimentent l’apprentissage automatique et l’IA générative, rédigez de meilleurs prompts et vérifiez les résultats avant de les utiliser.",
    activity: "Write one vague prompt and one improved prompt with audience, purpose, constraints, and output format. Compare the answers and list two facts that still need verification.",
    topics: [
      { term: "Training data", definition: "Examples used by an AI system to learn patterns; poor, incomplete, or biased examples can lead to unreliable results." },
      { term: "Generative AI", definition: "A model that creates new text, images, code, audio, or other content in response to instructions and context." },
      { term: "Verification", definition: "Checking an AI output against trustworthy sources, testing calculations or code, and applying human judgment before relying on it." },
    ],
  },
];
