export const senegalLessons = [
  {
    slug: "senegal-01-computer-skills", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 1,
    title: "Technology Education & Computer Skills", sourceUrl: "https://docs.google.com/presentation/d/1S5J0sA1qTY_H5i3NnVspDRzC4t35oyWL/edit", duration: 60,
    summary: "Start with the digital divide, essential computer parts, safe device handling, and the practical technology skills that support communication, learning, and earning.",
    summarySw: "Anza kwa kuelewa pengo la kidijitali, sehemu muhimu za kompyuta, matumizi salama ya kifaa na ujuzi wa teknolojia unaosaidia mawasiliano, kujifunza na kipato.",
    summaryFr: "Commencez par la fracture numérique, les composants essentiels d’un ordinateur, l’utilisation sûre des appareils et les compétences utiles pour apprendre, communiquer et travailler.",
    activity: "In pairs, point to each available computer component and explain its input, processing, storage, or output role. Finish by demonstrating a safe startup and shutdown.",
    topics: [
      { term: "Digital divide", definition: "The gap in access to devices, connectivity, and skills that prevents some communities from benefiting fully from technology." },
      { term: "Technology education", definition: "Learning to use, understand, and create with digital tools so people become confident problem-solvers rather than passive users." },
      { term: "Computer system", definition: "A combination of input devices, processing, storage, output devices, and software working together to complete tasks." },
    ],
  },
  {
    slug: "senegal-02-understanding-users", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 2,
    title: "Understanding a User’s Mind", sourceUrl: "https://docs.google.com/presentation/d/1avmwq0bGywyoZloXFa_cNl14rdeMox3I/edit", duration: 60,
    summary: "Design for real people by considering their intent, expectations, attention, emotions, and prior experience instead of choosing visuals only because they look attractive.",
    summarySw: "Buni kwa kuzingatia watu halisi: nia, matarajio, umakini, hisia na uzoefu wao wa awali badala ya kuchagua mwonekano kwa uzuri pekee.",
    summaryFr: "Concevez pour de vraies personnes en tenant compte de leurs intentions, attentes, émotions et expériences, plutôt qu’en choisissant des éléments uniquement parce qu’ils sont beaux.",
    activity: "Observe two versions of the same screen for ten seconds. Record what you noticed first, what action seemed possible, and which design better supported the user’s goal.",
    topics: [
      { term: "Mental model", definition: "A user’s expectation of how something should work, built from earlier experiences with similar tools and patterns." },
      { term: "User intent", definition: "The real goal a person wants to accomplish when they open a page, application, or service." },
      { term: "Visual hierarchy", definition: "The deliberate use of size, contrast, spacing, and placement to guide attention from the most important content to supporting details." },
    ],
  },
  {
    slug: "senegal-03-social-media-presence", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 3,
    title: "Social Media & Digital Presence", sourceUrl: "https://docs.google.com/presentation/d/1baWEYjJtx8ihhhqmF5y1nGdpMXm0LJ13/edit", duration: 60,
    summary: "Use free social platforms to communicate across distance, share work consistently, build trust, and discover opportunities while keeping a professional identity.",
    summarySw: "Tumia majukwaa ya kijamii kuwasiliana kwa mbali, kushiriki kazi kwa uthabiti, kujenga uaminifu na kupata fursa huku ukidumisha utambulisho wa kitaalamu.",
    summaryFr: "Utilisez les plateformes sociales pour communiquer à distance, partager votre travail régulièrement, établir la confiance et découvrir des opportunités tout en gardant une identité professionnelle.",
    activity: "Draft a professional profile: one-sentence purpose, three skills, one proof-of-work post, and a safe call to action. Review it with a partner before publishing anything.",
    topics: [
      { term: "Digital presence", definition: "The combined impression created by your profiles, posts, portfolio, and interactions across online platforms." },
      { term: "Consistent publishing", definition: "Sharing useful, relevant work on a sustainable schedule so an audience can understand your focus and trust your commitment." },
      { term: "Engagement", definition: "Meaningful audience actions such as saves, comments, replies, shares, or conversations—not only the number of followers." },
    ],
  },
  {
    slug: "senegal-04-ai-concepts", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 4,
    title: "AI Usage & Key Concepts", sourceUrl: "https://docs.google.com/presentation/d/1QbsGGv5GmkZTuOtJFtXa3SHjP5RkC0FR/edit", duration: 60,
    summary: "Learn what AI and large language models do, how transformer-based systems learn patterns, and why useful AI work still requires clear instructions and human checking.",
    summarySw: "Jifunze AI na modeli kubwa za lugha hufanya nini, jinsi mifumo ya transformer hujifunza mifumo na kwa nini matumizi bora bado yanahitaji maelekezo wazi na uhakiki wa binadamu.",
    summaryFr: "Découvrez ce que font l’IA et les grands modèles de langage, comment les transformeurs apprennent des régularités et pourquoi l’usage utile exige des consignes claires et une vérification humaine.",
    activity: "Ask an AI tool the same question twice: first with no context, then with audience, constraints, and format. Highlight what improved and verify one important claim.",
    topics: [
      { term: "Large language model", definition: "A model trained on large collections of text to predict and generate language for tasks such as explanation, drafting, translation, and coding." },
      { term: "Transformer", definition: "A neural-network architecture that uses attention to weigh relationships between parts of an input and preserve useful context." },
      { term: "Responsible use", definition: "Protecting personal data, checking accuracy and bias, naming AI assistance when appropriate, and keeping people accountable for final decisions." },
    ],
  },
  {
    slug: "senegal-05-canva-design", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 5,
    title: "Canva & Digital Design", sourceUrl: "https://docs.google.com/presentation/d/1X6D6h9kHH5pqo_WvvYNLNkUzIohEm7Be/edit", duration: 60,
    summary: "Create clear visual communication in Canva by starting from purpose, choosing a strong template, and keeping typography, color, imagery, and branding consistent.",
    summarySw: "Unda mawasiliano ya kuona yaliyo wazi katika Canva kwa kuanza na lengo, kuchagua kiolezo bora na kudumisha uthabiti wa herufi, rangi, picha na chapa.",
    summaryFr: "Créez une communication visuelle claire dans Canva en partant de l’objectif, en choisissant un bon modèle et en gardant une typographie, des couleurs et une identité cohérentes.",
    activity: "Create a one-page community event poster with one headline, three essential details, one call to action, and a limited palette. Test if a partner understands it in five seconds.",
    topics: [
      { term: "Design purpose", definition: "The audience, message, and action a visual must support; every design decision should make that purpose easier to understand." },
      { term: "Brand consistency", definition: "Repeated use of a defined logo, color palette, typography, voice, and spacing so materials feel connected and recognizable." },
      { term: "Template", definition: "A reusable starting layout that speeds up production but still needs thoughtful editing to fit the actual audience and message." },
    ],
  },
  {
    slug: "senegal-06-personal-portfolio", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 6,
    title: "Creating a Personal Portfolio", sourceUrl: "https://docs.google.com/presentation/d/18nKlnefBLOIgJR8Tq57pB9oQpBwaHzq3/edit", duration: 60,
    summary: "Plan and publish a simple personal website that explains who you are, proves what you can do through projects, and gives visitors a clear way to contact you.",
    summarySw: "Panga na uchapishe tovuti rahisi binafsi inayoeleza wewe ni nani, kuonyesha uwezo wako kupitia miradi na kuwapa wageni njia wazi ya kuwasiliana nawe.",
    summaryFr: "Planifiez et publiez un site personnel simple qui vous présente, prouve vos compétences grâce à des projets et offre un moyen clair de vous contacter.",
    activity: "Sketch a one-page portfolio on paper with About, Skills, Projects, and Contact sections. For one project, write the problem, your contribution, and the result.",
    topics: [
      { term: "Portfolio", definition: "A curated collection of work that demonstrates skills through evidence, context, process, and results rather than claims alone." },
      { term: "Information architecture", definition: "The organization and labeling of content so visitors can quickly understand where they are and where to find what they need." },
      { term: "Call to action", definition: "A specific next step—such as contact, download, or view project—that is clearly visible and easy for a visitor to complete." },
    ],
  },
  {
    slug: "senegal-07-copyright", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 7,
    title: "Copyright & Protecting Your Work", sourceUrl: "https://docs.google.com/presentation/d/13wrVCccrVoRaUxKwTVQZJ_H0Y5OIfhPQ/edit", duration: 60,
    summary: "Recognize creative work protected by copyright, document your own creation process, seek permission before reuse, and understand why business registration differs by country.",
    summarySw: "Tambua kazi za ubunifu zinazolindwa na hakimiliki, hifadhi ushahidi wa mchakato wako, omba ruhusa kabla ya kutumia kazi ya mwingine na elewa usajili wa biashara hutofautiana kwa nchi.",
    summaryFr: "Identifiez les œuvres protégées par le droit d’auteur, conservez des preuves de votre création, demandez l’autorisation avant toute réutilisation et comprenez que l’immatriculation varie selon le pays.",
    activity: "Review four sample assets for a business poster. Decide which you created, licensed, may use with attribution, or should replace. Record the source for every accepted asset.",
    topics: [
      { term: "Copyright", definition: "Legal protection that gives creators control over copying, distributing, adapting, displaying, or monetizing an original work." },
      { term: "License", definition: "Permission that states how another person may use a work, including conditions such as payment, attribution, or limits on modification." },
      { term: "Attribution", definition: "A clear credit naming the creator and source; it is required by some licenses but does not replace permission when permission is needed." },
    ],
  },
  {
    slug: "senegal-08-cybersecurity", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 8,
    title: "Introduction to Cybersecurity", sourceUrl: "https://docs.google.com/presentation/d/19xuIVjLvuo8B3YfvqwtM6zCpv7l5eH_F/edit", duration: 60,
    summary: "Protect accounts and information by recognizing phishing and social engineering, using layered security, and responding calmly when a message creates urgency or fear.",
    summarySw: "Linda akaunti na taarifa kwa kutambua ulaghai wa phishing na uhandisi wa kijamii, kutumia ulinzi wa tabaka nyingi na kujibu kwa utulivu ujumbe unaotishia au kuharakisha.",
    summaryFr: "Protégez vos comptes et vos données en reconnaissant le hameçonnage et l’ingénierie sociale, en utilisant plusieurs protections et en gardant votre calme face aux messages urgents.",
    activity: "Inspect three sample messages. Circle urgency cues, suspicious links, requests for secrets, and identity clues. Describe the safest verification path without clicking anything.",
    topics: [
      { term: "Phishing", definition: "A deceptive message or site that impersonates a trusted source to steal information, money, or account access." },
      { term: "Multi-factor authentication", definition: "A second proof of identity beyond a password, reducing harm when a password is guessed, reused, or stolen." },
      { term: "Social engineering", definition: "Manipulating people through trust, fear, urgency, or authority so they reveal information or perform an unsafe action." },
    ],
  },
  {
    slug: "senegal-09-task-automation", track: "Senegal Digital Entrepreneurship", trackSlug: "senegal-entrepreneurship", week: 9,
    title: "Task Automation for Small Teams", sourceUrl: "https://docs.google.com/presentation/d/1LXypjSg_yVJmPks0e2TxExXFUssAqQj8/edit", duration: 60,
    summary: "Use no-code automation as a force multiplier for small teams by mapping repetitive work, selecting triggers and actions, and protecting the quality of stored data.",
    summarySw: "Tumia uendeshaji wa kazi bila msimbo kuongeza uwezo wa timu ndogo kwa kuchora kazi zinazojirudia, kuchagua vichocheo na vitendo na kulinda ubora wa data.",
    summaryFr: "Utilisez l’automatisation sans code comme multiplicateur pour les petites équipes en cartographiant les tâches répétitives, les déclencheurs, les actions et la qualité des données.",
    activity: "Map one real business process from request to completion. Mark every repeated manual step, then propose one Zap while keeping a human approval before any high-impact action.",
    topics: [
      { term: "Force multiplier", definition: "A tool or process that lets a small team complete more reliable work without increasing effort at the same rate." },
      { term: "Zap", definition: "A Zapier workflow made from a trigger and one or more actions that move or transform information between applications." },
      { term: "Human checkpoint", definition: "A planned review before an automated process sends, deletes, pays, publishes, or otherwise performs a high-impact action." },
    ],
  },
];
